<a href="https://colab.research.google.com/github/Asrithakodam/Asrithakodam/blob/main/Lab_01PnS(1288).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=[1,2,34,6,32,14,65,7]
arr=np.array(a)
print(arr)

[ 1  2 34  6 32 14 65  7]


In [ ]:
arr=np.array([1,2,34,6,32,14,65,7])
print(arr)

[ 1  2 34  6 32 14 65  7]


In [ ]:
print(arr[0])
print(arr[2])

1
34


In [ ]:
aa=[[1,2,3,4],[4,2,3,6]]
A=np.array(aa)
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [ ]:
A=np.array([[1,2,3,4],[4,2,3,6]])
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [ ]:
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
np.ndim(arr)

1

In [ ]:
np.ndim(A)

2

In [ ]:
print(np.size(arr))

8


In [ ]:
print(np.size(A))

8


In [ ]:
print(np.shape(arr))

(8,)


In [ ]:
print(np.shape(A))

(2, 4)


In [ ]:
A=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [ ]:
print(A[0,:])
print(A[1,:])
print(A[2,:])

[1 2 3]
[3 4 5]
[4 5 6]


In [ ]:
print(A[:,0])
print(A[:,1])
print(A[:,2])

[1 3 4]
[2 4 5]
[3 5 6]


In [ ]:
print(A[2,1])

5


In [ ]:
import pandas as pd

In [ ]:
Dataset={
"State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
"Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
"Literacy %": [89, 77, 82, 97,85],
"Avg High Temp(c)": [33, 30, 29, 31, 32 ]}
print(Dataset)

{'State': ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'], 'Capital': ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'], 'Literacy %': [89, 77, 82, 97, 85], 'Avg High Temp(c)': [33, 30, 29, 31, 32]}


In [ ]:
df=pd.DataFrame(Dataset)
print(df)

            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32


In [ ]:
df=pd.DataFrame({
    "State": ['Andhra Pradesh','Maharashtra','Karnataka','Kerala','Tamil Nadu'],
    "Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
    "Literacy %": [89,77,82,97,85],
    "Avg High Temp(c)": [33,30,29,31,32]
})
print(df)


            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32


In [ ]:
print(df.head(2))

            State    Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh  Hyderabad          89                33
1     Maharashtra     Mumbai          77                30


In [ ]:
print(df.tail(3))

        State     Capital  Literacy %  Avg High Temp(c)
2   Karnataka   Bengaluru          82                29
3      Kerala  Trivandrum          97                31
4  Tamil Nadu     Chennai          85                32


In [ ]:
print(df.dtypes)

State               object
Capital             object
Literacy %           int64
Avg High Temp(c)     int64
dtype: object


In [ ]:
print(df.sort_values('Literacy %',ascending=False))

            State     Capital  Literacy %  Avg High Temp(c)
3          Kerala  Trivandrum          97                31
0  Andhra Pradesh   Hyderabad          89                33
4      Tamil Nadu     Chennai          85                32
2       Karnataka   Bengaluru          82                29
1     Maharashtra      Mumbai          77                30


In [ ]:
print(df[['Capital']])

      Capital
0   Hyderabad
1      Mumbai
2   Bengaluru
3  Trivandrum
4     Chennai


In [ ]:
print(df[['State', 'Capital']])

            State     Capital
0  Andhra Pradesh   Hyderabad
1     Maharashtra      Mumbai
2       Karnataka   Bengaluru
3          Kerala  Trivandrum
4      Tamil Nadu     Chennai


In [ ]:
print(df.loc[2])

State               Karnataka
Capital             Bengaluru
Literacy %                 82
Avg High Temp(c)           29
Name: 2, dtype: object


In [ ]:
print(df.iloc[2])

State               Karnataka
Capital             Bengaluru
Literacy %                 82
Avg High Temp(c)           29
Name: 2, dtype: object


In [ ]:
print(df.iloc[1,2])

77


In [ ]:
print(df.loc[1,'Literacy %'])

77


In [ ]:
a={"Distance":[15, 13, 16, 16, 15, 16, 17, 14, 15, 16, 16,17, 14, 17, 17, 16, 14, 15, 16, 17, 14, 16, 15, 17, 1]}