<a href="https://colab.research.google.com/github/Asrithakodam/Asrithakodam/blob/main/Pns1_1288.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Numpy Library


In [1]:
import numpy as np


Create an array :

In [2]:
a=[1,2,34,6,32,14,65,7]
arr=np.array(a)
print(arr)


[ 1  2 34  6 32 14 65  7]


In [3]:
arr=np.array([1,2,34,6,32,14,65,7])
print(arr)

[ 1  2 34  6 32 14 65  7]


In [4]:
print(arr[0])
print(arr[2])

1
34


Create a 2D array (Matrix)

In [5]:
aa=[[1,2,3,4],[4,2,3,6]]
A=np.array(aa)
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [6]:
A=np.array([[1,2,3,4],[4,2,3,6]])
print(A)

[[1 2 3 4]
 [4 2 3 6]]


In [7]:
print(type(A))

<class 'numpy.ndarray'>


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
np.ndim(arr)


1

In [10]:
np.ndim(A)

2

In [11]:
print(np.size(arr))

8


In [12]:
print(np.size(A))

8


In [13]:
print(np.shape(arr))

(8,)


In [14]:
print(np.shape(A))

(2, 4)


In [15]:
A=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [16]:
print(A[0,:])
print(A[1,:])
print(A[2,:])

[1 2 3]
[3 4 5]
[4 5 6]


In [17]:
print(A[:,0])
print(A[:,1])
print(A[:,2])

[1 3 4]
[2 4 5]
[3 5 6]


In [18]:
print(A[2,1])

5


Pandas Library

In [19]:
import pandas as pd

In [21]:
Dataset={
   "State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
   "Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
   "Literacy %": [89, 77, 82, 97,85],
   "Avg High Temp(c)": [33, 30, 29, 31, 32 ]}
print(Dataset)


{'State': ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'], 'Capital': ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'], 'Literacy %': [89, 77, 82, 97, 85], 'Avg High Temp(c)': [33, 30, 29, 31, 32]}


In [22]:
df = pd.DataFrame(Dataset)
print(df)

            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32


In [23]:
df = pd.DataFrame({
   "State": ['Andhra Pradesh', 'Maharashtra', 'Karnataka', 'Kerala', 'Tamil Nadu'],
   "Capital": ['Hyderabad', 'Mumbai', 'Bengaluru', 'Trivandrum', 'Chennai'],
   "Literacy %": [89, 77, 82, 97,85],
   "Avg High Temp(c)": [33, 30, 29, 31, 32 ]
})
print(df)


            State     Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh   Hyderabad          89                33
1     Maharashtra      Mumbai          77                30
2       Karnataka   Bengaluru          82                29
3          Kerala  Trivandrum          97                31
4      Tamil Nadu     Chennai          85                32


In [25]:
print(df.head(2))

            State    Capital  Literacy %  Avg High Temp(c)
0  Andhra Pradesh  Hyderabad          89                33
1     Maharashtra     Mumbai          77                30


In [26]:
print(df.tail(3))

        State     Capital  Literacy %  Avg High Temp(c)
2   Karnataka   Bengaluru          82                29
3      Kerala  Trivandrum          97                31
4  Tamil Nadu     Chennai          85                32


In [27]:
print(df.dtypes)

State               object
Capital             object
Literacy %           int64
Avg High Temp(c)     int64
dtype: object


In [28]:
print(df.sort_values('Literacy %', ascending=False))


            State     Capital  Literacy %  Avg High Temp(c)
3          Kerala  Trivandrum          97                31
0  Andhra Pradesh   Hyderabad          89                33
4      Tamil Nadu     Chennai          85                32
2       Karnataka   Bengaluru          82                29
1     Maharashtra      Mumbai          77                30


In [29]:
print(df[['Capital']])


      Capital
0   Hyderabad
1      Mumbai
2   Bengaluru
3  Trivandrum
4     Chennai


In [30]:
print(df[['State', 'Capital']])


            State     Capital
0  Andhra Pradesh   Hyderabad
1     Maharashtra      Mumbai
2       Karnataka   Bengaluru
3          Kerala  Trivandrum
4      Tamil Nadu     Chennai


In [31]:
print(df.loc[2])


State               Karnataka
Capital             Bengaluru
Literacy %                 82
Avg High Temp(c)           29
Name: 2, dtype: object


In [32]:
print(df.iloc[2])

State               Karnataka
Capital             Bengaluru
Literacy %                 82
Avg High Temp(c)           29
Name: 2, dtype: object


In [33]:
print(df.iloc[1,2])


77


In [34]:
print(df.loc[1,'Literacy %'])

77
